### ISSUE TITLE
Is it possible to ignore Ok and Error for default SwaggerGenerator

### ISSUE THREAD

**Issue by Eternal-ll** [edjCase/JsonRpc#104]
Hey, pretty cool library that solved some of my problems with JSON-RPC protocol over Http. I wanted to try to do something interesting, like mapping restful API with json-rpc on Swagger, but i met some difficulties. Spend time to debugging the errors and found out that RpcController doesnt hide Ok/Error and when using default SwaggerGenerator, it throws errors:
![image](https://user-images.githubusercontent.com/86099479/180612954-144bc497-f287-4ca8-baf3-3d2ea34c277e.png)
as workaround i made subclass and override it additional [NonAction] attributes, 
![image](https://user-images.githubusercontent.com/86099479/180613088-dcf5bb37-8246-4221-a175-e2bd708b9466.png)
it works now, but now they appear on Swagger docs with JSON-RPC :D 

![image](https://user-images.githubusercontent.com/86099479/180613117-3c8e0746-2f82-4e2e-802e-ee539d731f7d.png)

but at least it works

**Comment by Eternal-ll** [comment]
i guess this can be done differently, by adding [NonAction] to base class and ignore them in JsonRpcSwaggerProvider?

**Comment by Gekctek** [comment]
@Eternal-ll I cannot reproduce the issue you are having. Checking/debugging the code, it specifically excludes the RpcController methods. The sample project has some RpcController inherited classes, but they do not have that issue
In any case I added the [NonRpcMethod] attribute to be used in cases where the method needs to be hidden, but doesnt directly change your issue
I updated the Sample with the usage

If you can get me sample code or something to reproduce that I can help, otherwise try the [NonRpcMethod]

**Comment by Eternal-ll** [comment]
> @Eternal-ll I cannot reproduce the issue you are having. Checking/debugging the code, it specifically excludes the RpcController methods. The sample project has some RpcController inherited classes, but they do not have that issue In any case I added the [NonRpcMethod] attribute to be used in cases where the method needs to be hidden, but doesnt directly change your issue I updated the Sample with the usage
> 
> If you can get me sample code or something to reproduce that I can help, otherwise try the [NonRpcMethod]

Hi! Thank you for your reply, i made a sample project with my current edits. You will find required issue in WeatherForecastController with ApiExplorerSettings for controller

**Comment by Eternal-ll** [comment]
Oh i just noticed NonRpcMethod, it will help! Sorry, we can close this issue now

**Comment by Gekctek** [comment]
Weird. Still unable to reproduce it 
I uncommented it but still dont see it
![image](https://user-images.githubusercontent.com/1934953/181081791-088d35f2-e905-4a49-9740-974062311520.png)
![image](https://user-images.githubusercontent.com/1934953/181081909-c6843689-d8a0-484c-859a-33ff1980c8f3.png)

but if the NonRpcMethod works then lets go with that

**Comment by Eternal-ll** [comment]
Very strange,  that is what happens to me on start on JSON API schema, not in json-rpc: 
![image](https://user-images.githubusercontent.com/86099479/181087188-a1ab8a41-af4d-47bd-87c3-40417bd6f7d3.png)
