### ISSUE TITLE
Сondition is unnecessary 

### ISSUE THREAD

**Issue by and1helicopter** [edjCase/JsonRpc#107]
I think the first condition is unnecessary as the query won't work with optional parameters.

https://github.com/edjCase/JsonRpc/blob/ba632691ddd4180a49b4fa6be4327682244ab225/src/EdjCase.JsonRpc.Router/Defaults/DefaultRpcInvoker.cs#L264-L272

**Comment by Gekctek** [comment]
Let me know if this works 
https://www.nuget.org/packages/EdjCase.JsonRpc.Router/5.1.4
