### ISSUE TITLE
DefaultRequestMatcher. System.ArgumentNullException for basePath

### ISSUE THREAD

**Issue by amoraller** [edjCase/JsonRpc#116]
If i want use RpcController without path and routing, i have exception ArgumentNullException in DefaultRequestMatcher, 
because rpcPath is null.

i think, if rpcPath  mabye "null", we should support null value anyware

![image](https://user-images.githubusercontent.com/7438667/227989021-53805fea-2757-41ea-9782-308bc10bc8e3.png)

**Comment by Gekctek** [comment]
@amoraller There are some subtle differences between the string version and the RpcPath version.
But in this case it looks to be ok, so ill merge your PR

As far as the details, I would have to review some of this. I worked on this years ago and tried to optimize some performance without knowing too much what I was doing lol, but we can change anything that seems to be an issue

**Comment by Gekctek** [comment]
Try version 5.1.6
