### ISSUE TITLE
Incorrect response with RpcErrors

### ISSUE THREAD

**Issue by amoraller** [edjCase/JsonRpc#118]
I have a problem with request validation:
If request value is non-JsonRpc object(no version property)  library return null value. At specification JSON-RPC 2.0 (https://www.jsonrpc.org/specification), if we can not parse or validate request, we **sould** return response object with error data

for req
![image](https://user-images.githubusercontent.com/7438667/229086252-37731ccd-f23b-483a-be2c-6c17684829f8.png)

for batch 
![image](https://user-images.githubusercontent.com/7438667/229086171-745f7b2a-0900-4555-aaaf-6e045806e0f1.png)

i think problem in RpcRequestHandler.HandleRequestAsync on error request processing:
if result has any error, we don`t should test id of **default** value

![image](https://user-images.githubusercontent.com/7438667/229090305-946c447f-ae41-4dd5-af55-f75b210e1f83.png)

**Comment by amoraller** [comment]
And  i think we sould add RpcRequestHandler tests

**Comment by Gekctek** [comment]
@amoraller What is the exact request that is failing for you. 
The code you highlighted is errors returned from invoking the methods, not the parsing of the requests.
The parsing of the requests throws an RpcException that gets caught in the RpcRequestHandler and returns a single response with no id
```cs
catch (RpcException ex)
			{
				this.logger.LogException(ex, "Error occurred when proccessing Rpc request. Sending Rpc error response");
				var response = new RpcResponse(new RpcId(), ex.ToRpcError(this.serverConfig.Value.ShowServerExceptions));
				await this.responseSerializer.SerializeAsync(response, responseBody);
			}
			```

**Comment by amoraller** [comment]
For examlpe, if i send empty json **"{}"**, 
library is correct parse input, and return RpcRequestParseResult with null-value **id**. 
RpcRequestHandler.HandleRequestAsync not write responce, because responce no have **id**.
In specification, if we have invalid request we MUST send responce with null id property.

![image](https://user-images.githubusercontent.com/7438667/229700226-c4f4c3de-c02c-4e3a-a9dd-b43d7781f5b2.png)

**Comment by Gekctek** [comment]
@amoraller im not sure if thats right. In the first sentence `MUST reply with a Response, except for in the case of Notifications.`
And earlier in the spec it says 
```
A Notification is a Request object without an "id" member. A Request object that is a Notification signifies the Client's lack of interest in the corresponding Response object, and as such no Response object needs to be returned to the client. The Server MUST NOT reply to a Notification, including those that are within a batch request.

Notifications are not confirmable by definition, since they do not have a Response object to be returned. As such, the Client would not be aware of any errors (like e.g. "Invalid params","Internal error").
```

I think the sentence you marked only applies to there being an Id, but it cant be parsed, or there was a problem parsing the entire object and it could not tell if there was an id or not. In the case where Id is null, then it shouldnt return anything.

What problem are you trying to solve

**Comment by amoraller** [comment]
Check pls this examples in specification 
![image](https://user-images.githubusercontent.com/7438667/230554072-e0b7907c-dbf2-4f2f-b6d7-1d075efae26c.png)
![image](https://user-images.githubusercontent.com/7438667/230554198-06f04079-0ef9-40b2-87a2-e2c6ec7a515c.png)

I think, we can determine, notify or request only aftet start executing.

**Comment by Gekctek** [comment]
I think the problem with my code is that I dont differentiate between invalid requests and valid requests with no id. Ill see what i can do

**Comment by Gekctek** [comment]
Try 
https://github.com/edjCase/JsonRpc/releases/tag/5.1.7
