### ISSUE TITLE
Blackduck security issues on JJsonRpc

### ISSUE THREAD

**Issue by MikeMillerDevices** [edjCase/JsonRpc#127]
Hi,
There are some new vulnerabilities reported on Microsoft libraries you've referenced we are currently using JsonRpc 6.0.1. Can you update to the latest?

These are the vulnerabilities:
https://github.com/advisories/GHSA-8g4q-xg66-9fp4
https://github.com/advisories/GHSA-qj66-m88j-hmgj

Thanks for your help,

**Comment by Gekctek** [comment]
https://github.com/edjCase/JsonRpc/releases/tag/6.0.2

Should be on Nuget shortly

**Comment by MikeMillerDevices** [comment]
Thanks for the fast turn around
