### ISSUE TITLE
Ability to change the Content-Type header

### ISSUE THREAD

**Issue by slothbag** [edjCase/JsonRpc#20]
I need to be able to change the Content-Header from text/plain to application/json.. can this be exposed in the RpcClient?

**Comment by juanfranblanco** [comment]
this fixes the issue https://github.com/Nethereum/Nethereum/blob/33c0a0c90cff2db18372af25d46c34f726e1e4e0/src/Nethereum.JsonRpc.Client/RpcClient.cs#L139-L140

**Comment by Gekctek** [comment]
Let me know if this meets all your requirements

**Comment by slothbag** [comment]
It looks like it should do the trick.  Thanks.
