### ISSUE TITLE
Portable Library of the Rpc Client and Core

### ISSUE THREAD

**Issue by juanfranblanco** [edjCase/JsonRpc#21]
Will it be possible to have a portable library of the client and core. Hopefully now things have settled with netstandard, and core release.

**Comment by Gekctek** [comment]
Not sure if I understand fully. Do you need a Portable Class Library for them. Does netstandard not work for what you are doing?

**Comment by juanfranblanco** [comment]
Yes, netstandard is not widely available, my current workaround is having a new project which includes all the files for all the projects linked, my only dependency not portable are your projects. But if is too much bother,  do not worry. I can continue this way until settles down netstandard :)

On 23 Jul 2016 22:21, Ethan Celletti <notifications@github.com> wrote:Not sure if I understand fully. Do you need a Portable Class Library for them. Does netstandard not work for what you are doing?

**Comment by Gekctek** [comment]
I was able to add the .NETPortable,Version=v4.5,Profile=Profile111 framework to it. Hopefully that works for you. All the pcl profiles are listed here https://docs.nuget.org/create/targetframeworks

**Comment by juanfranblanco** [comment]
Fantastic, let me try it
