### ISSUE TITLE
EdjCase vs edjCase

### ISSUE THREAD

**Issue by slothbag** [edjCase/JsonRpc#27]
Just wondering why all the source code specifies a namespace starting with edjCase but the code within the binaries from Nuget start with EdjCase?

This is causing me compatibility problems with compiling vs using nuget binaries.

Edit 1: Its not a big issue, I've updated my refs so its not a problem anymore.. still curious as to how this could happen though.

**Comment by Gekctek** [comment]
Im not seeing what you are in the latest code. It was at one point edjCase
because that is how I originally spelt it but changed it to EdjCase to be
consistent with other namespaces. But both the packages and the source code
should now be EdjCase.

**Comment by slothbag** [comment]
That makes sense. I must have been looking at an older repo version.

Thanks
