### ISSUE TITLE
Net Core 2.0 Authorize attribute.

### ISSUE THREAD

**Issue by b000924520004** [edjCase/JsonRpc#38]
Hello,    
The RESTful API for authorization validation works, but does not work at JsonRpc, send me the following information, using [AllowAnonymous] or working without authentication.
   
```cs
{"id":2,"jsonrpc":"2.0","result":null,"error":{"code":-32603,"message":"An internal server error has occurred\tInner Exception: Method not found: 'System.Threading.Tasks.Task`1<Boolean> Microsoft.AspNetCore.Authorization.AuthorizationServiceExtensions.AuthorizeAsync(Microsoft.AspNetCore.Authorization.IAuthorizationService, System.Security.Claims.ClaimsPrincipal, Microsoft.AspNetCore.Authorization.AuthorizationPolicy)'。","data":null}}
```  
   
My working environment : .Net Core2.0 , EdjCase.JsonRpc.Router 1.3.3   
Thx.

**Comment by Gekctek** [comment]
Ill try this out. I have been moving the Router over to .NetStandard 2

**Comment by Gekctek** [comment]
I have published Version 2.0.0. Try that out and see if it fixed the issue. Using Aspnet core 2 and packages that reference Aspnet core 1 is a bad combo apparently. That all should be fixed.
Something to be aware of is that I have been working on other changes of refactoring out HttpContext and other big changes, so it is a breaking change. I will be updating the readme soon. Let me know if there are any issues changing over

**Comment by Gekctek** [comment]
I have now updated the README file for the new configuration.

**Comment by b000924520004** [comment]
Currently using Version 2.0.0, it is working.
If there are problems will tell you again, thank you very much for your help.
