### ISSUE TITLE
Ability to add custom middleware to preprocess requests

### ISSUE THREAD

**Issue by marvel16** [edjCase/JsonRpc#42]
Is there a way to make custom middleware to catch json rpc requests like we can do that with mvc?
e.g.
public class RequestLoggingMiddleware 
{ 
    private readonly RequestDelegate _next; 
    private readonly ILogger<RequestLoggingMiddleware> _logger; 

    public RequestLoggingMiddleware(RequestDelegate next, ILogger<RequestLoggingMiddleware> logger) 
    { 
        _next = next; 
        _logger = logger; 
    } 

    public async Task Invoke(HttpContext context) 
    { 
        var startTime = DateTime.UtcNow; 

        var watch = Stopwatch.StartNew(); 
        await _next.Invoke(context); 
        watch.Stop(); 

        var logTemplate = @" 
Client IP: {clientIP} 
Request path: {requestPath} 
Request content type: {requestContentType} 
Request content length: {requestContentLength} 
Start time: {startTime} 
Duration: {duration}"; 

        _logger.LogInformation(logTemplate, 
            context.Connection.RemoteIpAddress.ToString(), 
            context.Request.Path, 
            context.Request.ContentType, 
            context.Request.ContentLength, 
            startTime, 
            watch.ElapsedMilliseconds); 
    } 
}

**Comment by marvel16** [comment]
RequestDelegate that is being passed to middleware makes the next point MVC framework, not RCP JSON.
Please, help to solve this issue.

**Comment by marvel16** [comment]
This was fixed with adding middleware inside json rpc app configuration: 

app..UseMiddleware<LoggingMiddleware>(); // here requests after middleware are forwared to MVC framework, not json rpc., so it needs to be added like this:

` app.Map("/api", rpcApp =>
            {
                rpcApp.UseMiddleware<LoggingMiddleware>();
                rpcApp.UseJsonRpc(builder =>
                {                    
                    builder.RegisterTypeRoute<Blablaclass>("/blabla");
}`

**Comment by Gekctek** [comment]
I have been wanting to do events in here, so i think a OnRequestStart event or something like that would help your issue, illl make it a new feature

**Comment by 2m0nd** [comment]
@Gekctek hi, need analog mvc middleware for application metrics with info method, route, time execution, status.
What if we extend the class RpcRequestHandler? If you give advice on how best to do i can implement this feature.

**Comment by Gekctek** [comment]
Ya, let me review this really quick. There is a pattern i like with creating optional events for different points in the pipeline like:
`class Events 
{
    Func<....> OnRequestStart {get; set;}
    Func<...> OnRequestEnd {get; set; }
    ...etc
}`cs

**Comment by Gekctek** [comment]
#83
