### ISSUE TITLE
Make matching controllers case-insensitive

### ISSUE THREAD

**Issue by queil** [edjCase/JsonRpc#46]
Is there any setting that would make matching controller names case-insensitive? I.e. I would like my ServiceAController to be matched both by e.g. http://localhost/ServiceA and http://localhost/servicea

**Comment by Gekctek** [comment]
Im suprised this was never caught by me or anyone else who uses this library. Good catch. It will be fixed in nuget version 2.1.4

**Comment by Gekctek** [comment]
https://www.nuget.org/packages/EdjCase.JsonRpc.Router/2.1.4

**Comment by queil** [comment]
Thanks!
