### ISSUE TITLE
Problem with scoped AuthorizationHandler

### ISSUE THREAD

**Issue by hey-red** [edjCase/JsonRpc#50]
When I'm try to implement custom [AuthorizationHandler](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.0#authorization-handlers), i'm getting the following exception:

`System.InvalidOperationException: "Cannot consume scoped service 'Microsoft.AspNetCore.Authorization.IAuthorizationHandler' from singleton 'EdjCase.JsonRpc.Router.Abstractions.IRpcInvoker'."`

**Comment by Gekctek** [comment]
Well that specific issue seems that the IRpcInvoker is registered as a Singleton while the IAuthorizationHandler is Scoped. But since the IRpcInvoker is singleton it only wants other services that are singleton. To fix this i think you can register your IAuthorizationHandler as singleton as well. Do you need the IAuthorizationHandler to be scoped? if so i can look into if i can allow that

**Comment by hey-red** [comment]
>Do you need the IAuthorizationHandler to be scoped?
Yes, handler requires dbcontext.

**Comment by Gekctek** [comment]
Ok ill take a look at it

**Comment by Gekctek** [comment]
Is it possible for you to show me your servicecollection/dependecy injection setup so i can make sure that I get it working correctly

**Comment by hey-red** [comment]
You can use default project template

Startup:

```C#
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;

namespace WebApplication1
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddJsonRpc(options =>
            {
                options.BatchRequestLimit = 3;
                options.ShowServerExceptions = true;
            });

            services.AddScoped<IAuthorizationHandler, CustomAuthorizationHandler>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseJsonRpc(config =>
            {
                config.BaseRequestPath = "rpc";
            });
        }
    }
}
```

Handler:

```C#
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using System;
using System.Threading.Tasks;

namespace WebApplication1
{
    public class CustomAuthorizationHandler : AuthorizationHandler<OperationAuthorizationRequirement>
    {
        protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, OperationAuthorizationRequirement requirement)
        {
            throw new NotImplementedException();
        }
    }
}
```

**Comment by Gekctek** [comment]
This should now be fixed in the latest master branch and in nuget version 2.1.8, let me know if there are any issues

**Comment by hey-red** [comment]
Yes, it works. Thanks!
