### ISSUE TITLE
Does the Client Support WebSocket ?

### ISSUE THREAD

**Issue by John0King** [edjCase/JsonRpc#64]
I'm writing an app that work in local  but the server need to communicate with me, the `WebSocket` is the way to go (server do not know my app's IP address)
So my app need to be a client that connect to server then the service can communicate  with my app.

Is the Client support webSocket ?

**Comment by Gekctek** [comment]
There is experimental websocket support for the client. The client has a
'Transport' interface that abstracts out the normal http client usage and
allows for others. I have implemented a websocket one but don't use it
myself so it may need some work/designing. If you are willing to try/use
it. I'll do my best to fix/add functionality

**Comment by John0King** [comment]
@Gekctek Thanks, I will try it , but I just peek a few line of the `WebSocketTransportClient`,  it may missing a very important concept of the WebSocket RPC :  "**Session**" .unlike the HTTP, the HTTP already take care of the session.
The Server side have multiple `Connection` and and each connection have multiple `Session`  , and the Client have one `Connection` and multiple `Session` , 

client ---------- id = 1   ------> server   (response take 2 sec)
client -----------id = 2 --------> server (response take 0.5 sec)
client <-----------id = 2 -------- server (response 2)
client <-----------id = 1 -------- server (response 1)

so in this case, The `Session` is a group that pair the request and response.

I'm not read all of your code , not sure how you handle this case.

**Comment by John0King** [comment]
Maybe I'm wrong ,  it seems like in `JsonRpc 2.0`  the server can not invoke client's method

**Comment by John0King** [comment]
To solve my current problem, I design a simple version of JsonRPC , it only support notification call , and it's peer to peer. 
http://www.simple-is-better.org/rpc/#differences-between-1-0-and-2-0  from this document,  the `JsonRPC 2.0` is not peer to peer anymore.
So I'm going to close this issue.
