### ISSUE TITLE
Not only RPC controller in the project

### ISSUE THREAD

**Issue by BigDaddy1337** [edjCase/JsonRpc#65]
Hi there, thanx for library. In my project there is a need to use other than rpc controllers.
But on an unregistered controller, an error occurs when I receive a REST request.

`Request with no id failed and no response will be sent. Error - Code: -32600, Message: The jsonrpc version must be specified.
`

This started to happen after upgrading from version 2.1.9 to 3.0.1.

my settings:
```
            services.AddJsonRpc().WithOptions(options =>
            {
                options.ShowServerExceptions = false;
                options.JsonSerializerSettings = new JsonSerializerSettings
                {
                    ContractResolver = new SnakeCasePropertyNamesContractResolver(),
                    NullValueHandling = NullValueHandling.Include,
                    Formatting = Formatting.Indented,
                    DefaultValueHandling = DefaultValueHandling.Include
                };

                var dateConverter = new IsoDateTimeConverter
                {
                    DateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.fff'Z'"
                };
                options.JsonSerializerSettings.Converters.Add(dateConverter);
            });

.........................

            app.UseManualJsonRpc(builder =>
            {
                builder.RegisterController<SomeController>("api/v1/private/somepath");
            });
```

Is it possible to ignore the rpc processing of some controllers?

**Comment by rushfive** [comment]
Can you clarify what you mean by "... processing of some controllers"?

If you're looking to mix endpoints, some using RPC and others using REST, that's very much possible. You'll just have to be careful not to configure things in a way where you have conflicting paths.

What's the REST endpoint path that you are _expecting_ the request to hit? can you provide a snippet of your REST controller class?

**Comment by BigDaddy1337** [comment]
@rushfive Hi, I have 1 endpoint json rpc (the configuration described above) and 1 standard endpoint with method. 

```
    [ApiController]
    [Route("api/v1/second")]
    public class SecondController: ControllerBase
```

When someone hit this standard endpoint - library throws error.

As a workaround, I transformed SecondController to json rpc and create middleware that converts the request body to json rpc standart for a specific path, but this... not elegant.. :)

**Comment by Gekctek** [comment]
Ill look into this, it must be assuming all requests are jsonrpc requests before it matches against a route.

**Comment by Gekctek** [comment]
Are the routes to the RpcController and the REST controller the same? The code logic looks to match the base url (in this case "api/v1/private/somepath") and if it has that base url then it will assume that it is an rpc request. Also if you could show me the Debug/Console output to the EdjCase code logs, that would also help me.

**Comment by Gekctek** [comment]
> Are the routes to the RpcController and the REST controller the same? The code logic looks to match the base url (in this case "api/v1/private/somepath") and if it has that base url then it will assume that it is an rpc request. Also if you could show me the Debug/Console output to the EdjCase code logs, that would also help me.

@BigDaddy1337

**Comment by BigDaddy1337** [comment]
@Gekctek routes different,
_api/v1/private/somepath_ - route for JSON RPC, with manual registration (UseManualJsonRpc)
_api/v1/second/methodname_ - route for REST controller with POST method, which used by external service, who can't switch to jsonrpc

log, when that happend

```
2019-03-27 17:42:37.192 +05:00 [INF] Request starting HTTP/1.1 POST http://my-server-address/api/v1/second/methodname application/json; charset=UTF-8 776
2019-03-27 17:42:37.192 +05:00 [INF] Rpc request with route '/api/v1/second/methodname' started.
2019-03-27 17:42:37.193 +05:00 [INF] Processing 1 Rpc requests
2019-03-27 17:42:37.193 +05:00 [ERR] Request with no id failed and no response will be sent. Error - Code: -32600, Message: The jsonrpc version must be specified.
2019-03-27 17:42:37.195 +05:00 [INF] No rpc responses created.
2019-03-27 17:42:37.195 +05:00 [INF] Request finished in 3.544ms 204 
```
I apologize, I have already changed the code - I added middleware to convert the REST request to the JSON RPC format as a temporary solution, so I can not provide EdjCase logs, but I think the idea is clear

It would be cool to be able to mark endpoints as ignored for Json RPC, most likely it will affect the performance, so I'm not sure, maybe you will have an idea how easy it can be.

thanks for answer

**Comment by Gekctek** [comment]
Using the `UseManualJsonRpc` middleware should always ignore every controller and route unless it is specified. I am unable to reproduce the issue. so if you want me to fix it ill need code to debug.  So if you can send me some code or zipped project i can fix it.
