### ISSUE TITLE
ShowServerExceptions not working because of bug in creating RpcExceptions

### ISSUE THREAD

**Issue by jthakkaritbit** [edjCase/JsonRpc#66]
https://github.com/edjCase/JsonRpc/blob/0a3c3387da54b2d2b76e50415f9cb23316c328d7/src/EdjCase.JsonRpc.Core/RpcExceptions.cs#L45

The message string is correct, but this.Message never gets updated. Should be a quick fix. Or should I create a PR?

**Comment by Gekctek** [comment]
Sorry for the insanely late response. You can do a pr and I'll pull it in.
Good catch. Thank you

**Comment by george-paxos** [comment]
@Gekctek I'm picking up this change, I don't have access to push a remote branch. Is there another way to make a PR?

**Comment by Gekctek** [comment]
If you push it to your forked repo. You can do a PR to my repo

**Comment by george-paxos** [comment]
Cool thanks for responding so fast. BTW while on this exception topic - is there a way to prevent certain exceptions from being logged when calling OnExceptionResult.Use*** methods? We found the default stack trace to be a bit too noisy:

```
2019-08-09 19:11:04.3228|ERROR|Exchange|EdjCase.JsonRpc.Router.Utilities.LoggerExtensions.LogException|An Rpc error occurred while trying to invoke request.
   at EdjCase.JsonRpc.Router.Defaults.DefaultRpcInvoker.InvokeRequestAsync(RpcRequest request, RpcPath path, IRouteContext routeContext)|....... .........Exception: Exception of type '.........Exception' was thrown.
   at EdjCase.JsonRpc.Router.Defaults.DefaultRpcInvoker.InvokeAsync(RpcMethodInfo methodInfo, RpcPath path, IServiceProvider serviceProvider)
.
.
.
```

**Comment by Gekctek** [comment]
The `OnExceptionResult` has a property `ThrowException`. If that is set to false it shouldnt throw anything. but it will return whatever `ResponseObject` you give it to the client

**Comment by george-paxos** [comment]
But the c'tor is private, and the `ThrowException` property doesn't have a getter, how else can I set that?

**Comment by george-paxos** [comment]
I think this does it for me
```
var responseObj = new
            {
                ex.Message,
                Classname = ex.GetType().Name,
                StackTraceString = ex.StackTrace
            };

            if (_exceptionBlacklist.Contains(ex.GetType()))
            {
                return OnExceptionResult.UseMethodResultResponse(new RpcMethodErrorResult(422, ex.Message, responseObj));
            }
                return OnExceptionResult.UseMethodResultResponse(new RpcMethodErrorResult(422, ex.Message, responseObj));

```

**Comment by Gekctek** [comment]
Let me know if you need help with anything else
