### ISSUE TITLE
InvalidOperationException for EdjCase.JsonRpc.Router.Sample project

### ISSUE THREAD

**Issue by andreytreyt** [edjCase/JsonRpc#74]
I cloned a repo, built EdjCase.JsonRpc.Router.Sample project, run it, sent a request and received an exception.
System.InvalidOperationException: No service for type 'EdjCase.JsonRpc.Router.StaticRpcMethodDataAccessor' has been registered.

I created a new project and added package EdjCase.JsonRpc.Router 4.0.0.
My Program.cs contains this code:
```
public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
```
So I couldn't even run such project. I received exceptions.
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: EdjCase.JsonRpc.Router.Abstractions.IRpcInvoker Lifetime: Scoped ImplementationType: EdjCase.JsonRpc.Router.Defaults.DefaultRpcInvoker': Unable to resolve service for type 'EdjCase.JsonRpc.Router.Abstractions.IRpcMethodProvider' while attempting to activate 'EdjCase.JsonRpc.Router.Defaults.DefaultRequestMatcher'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'EdjCase.JsonRpc.Router.Abstractions.IRpcMethodProvider' while attempting to activate 'EdjCase.JsonRpc.Router.Defaults.DefaultRequestMatcher'.

There is no any word in the docs. Help me please.

**Comment by Gekctek** [comment]
Looks like there were missing DI items in the startup extensions. Unit testing didnt catch that. Pushing out version 4.0.1 to nuget now
