### ISSUE TITLE
 params is IEnumerable was worng

### ISSUE THREAD

**Issue by crazyiter** [edjCase/JsonRpc#75]
The Method Like this:
 
public List<Item> Add7(List<Item> items)
 {
    return items;
 }
public class Item
{
  public int a { get; set; }
  public int b { get; set; }
 }		
 
the request like this :
{
	"jsonrpc": "2.0",
	"id": 1,
	"method": "Add7",
	"params":  {
              "items": [{"a":12,"b":23},{"a":12,"b":23}] 
	}
}
the response  is:
{
    "id": 1,
    "jsonrpc": "2.0",
    "error": {
        "code": -32700,
        "message": "Invalid json",
        "data": null
    }
}
or  request is 
{
	"jsonrpc": "2.0",
	"id": 1,
	"method": "Add7",
	"params":    [{"a":12,"b":23},{"a":12,"b":23}]
		   
}

and respones is 
{
    "id": 1,
    "jsonrpc": "2.0",
    "error": {
        "code": -32601,
        "message": "No methods matched request.",
        "data": null
    }
}

**Comment by crazyiter** [comment]
Code in  Class  DefaultRpcParser  line 258:
Add 
case JsonTokenType.StartArray:
    paramType = RpcParameterType.Object;
    int originalDepths = jsonReader.CurrentDepth;
    while (jsonReader.TokenType != JsonTokenType.EndArray || jsonReader.CurrentDepth != originalDepths)
    {
	 jsonReader.Read();
    }
    break;

**Comment by Gekctek** [comment]
Published Nuget 4.0.2 package

**Comment by crazyiter** [comment]
Thank you!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Ethan Celletti <notifications@github.com>
发送时间: Tuesday, February 11, 2020 12:44:09 AM
收件人: edjCase/JsonRpc <JsonRpc@noreply.github.com>
抄送: crazyiter <crazyiter_bin@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [edjCase/JsonRpc] params is IEnumerable was worng (#75)


Closed #75<https://github.com/edjCase/JsonRpc/issues/75> via e380bee<https://github.com/edjCase/JsonRpc/commit/e380beed5a9e38d618a5916e1117ba7b7f2ba1fb>.

―
