### ISSUE TITLE
Will Newtonsoft.Json be adpated?

### ISSUE THREAD

**Issue by CSharpStudio** [edjCase/JsonRpc#92]
My projects used Newtonsoft.Json and now I have to add System.Text.Json for JsonRpc. I have to adapte two kinds of JsonConverter for custom serialize. System.Text.Json is too weak for customizing.

**Comment by Gekctek** [comment]
There is no plan to add customization for what serializer to use but in theory the `IRpcParser`/`IRpcResponseSerializer` can be swapped out/overridden to use whatever library is needed.
