### ISSUE TITLE
Optional parameters

### ISSUE THREAD

**Issue by s01omon** [edjCase/JsonRpc#99]
I try to get default value for the " fontFamily" property equals to "Arial" 
**Method:**
`public IRpcMethodResult CreateInfoHelperItem(
            string name,
            string language,
            string value,
            string description,
            string component,
            string locationIndex,
            string fontFamily = "Arial",
            int fontSize = 12,
            bool bold = false,
            bool italic = false,
            bool strikeout = false,
            bool underline = false
            ) =>
            Ok();`
**request:**
`{
    "jsonrpc": "2.0",
    "id": 123,
    "method": "CreateInfoHelperItem",
    "params": {
        "name": "test1",
        "language": "en",
        "value": "test1",
        "description": "test1",
        "component": "Policy",
        "locationIndex": "zazaPage",        
        "fontSize": 12,
        "bold": false,
        "italic": false,
        "strikeout": false,
        "underline": false
    }
}`
**Response:**
`{
    "id": 123,
    "jsonrpc": "2.0",
    "error": {
        "code": -32601,
        "message": "No methods matched request.",
        "data": null
    }
}`

**Comment by Gekctek** [comment]
https://www.nuget.org/packages/EdjCase.JsonRpc.Router/5.1.0

Fixed. Had some serious tech debt that I finally addressed. Revamped the entire request parsing/matching code.
Let me know if you have any issues @s01omon
